//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class customers_balance
    {
        public System.Guid customer_id { get; set; }
        public decimal balance { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
